name: test build status change
on:
  push:
    branches:
      - experimental/run_status

permissions:
  actions: read

jobs:
  fail_success:
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: exit 0
  second_job:
    needs:
      - fail_success
    runs-on: ubuntu-latest
    steps:
      - name: success
        run: exit 0
  status:
    needs:
      - second_job
    if: ${{ !cancelled() }}
    uses: ./.github/workflows/reusable-status.yaml
    secrets: inherit
