name: test build status change
on:
  push:
    branches:
      - experimental/run_status

permissions:
  contents: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo "Hello, world!"
      - name: Get Previous Run Status
        id: get_previous_status
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: runs } = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: context.workflow,
              per_page: 2,
              page: 1,
            });
            return runs[1].status;

      - name: Check Status Change
        id: check_status_change
        run: echo "Build back to normal"
        if: ${{ steps.get_previous_status.outputs.result != success() }}

      - name: Echo fail
        run: echo "Build failed"
        if: ${{ failure() && !cancelled() }}
