name: test build status change
on:
  push:
    branches:
      - experimental/run_status

permissions:
  contents: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: run
        run: |
          echo "Hello, world!"
      - name: Get Previous Run Status
        id: get_previous_status
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const path = require('path');
            let workflow_ref = process.env.GITHUB_WORKFLOW_REF;
            const workflow_id = path.basename(workflow_ref.split('@')[0]);

            const { data: runs } = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: workflow_id,
              per_page: 2,
              page: 1,
            });
            return runs.workflow_runs[1].status;

      - name: Check Status Change
        id: check_status_change
        run: echo "Build back to normal"
        if: ${{ steps.get_previous_status.outputs.result != success() }}

      - name: Echo fail
        run: echo "Build failed"
        if: ${{ failure() && !cancelled() }}
